<?php
/**
 * Block-editor asset wiring (Flinkform Pro).
 *
 * Enqueues the Pro editor script that docks onto the free core's editor
 * extension points (the `flinkform.formContainer.inspectorPanels` filter and
 * those added in later slices). The script is a dependency-light vanilla
 * `wp.*` bundle — see assets/editor.js for the rationale.
 *
 * @package FlinkformPro
 * @since 0.2.2
 */

declare( strict_types = 1 );

namespace FlinkformPro\Editor;

defined( 'ABSPATH' ) || exit;

/**
 * Registers Flinkform Pro's block-editor assets.
 */
final class Extensions {

	private const HANDLE = 'flinkform-pro-editor';

	/**
	 * Register the WordPress hooks.
	 *
	 * @return void
	 */
	public function register(): void {
		add_action( 'enqueue_block_editor_assets', [ $this, 'enqueue' ] );
	}

	/**
	 * Enqueue the Pro editor extension bundle.
	 *
	 * Loads on every block-editor screen; the registered filters only fire for
	 * Flinkform blocks that apply them, so this is inert everywhere else. The
	 * dependency list + cache-busting version come from the build manifest
	 * (`build/index.asset.php`) generated by @wordpress/scripts.
	 *
	 * @return void
	 */
	public function enqueue(): void {
		$asset_file = FLINKFORM_PRO_DIR . 'build/index.asset.php';
		if ( ! is_readable( $asset_file ) ) {
			return;
		}

		/** @var array{dependencies: array<int, string>, version: string} $asset */
		$asset = require $asset_file;

		wp_enqueue_script(
			self::HANDLE,
			FLINKFORM_PRO_URL . 'build/index.js',
			$asset['dependencies'] ?? [],
			$asset['version'] ?? FLINKFORM_PRO_VERSION,
			true
		);

		wp_set_script_translations( self::HANDLE, 'flinkform-pro' );
	}
}
