<?php
/**
 * GDPR / DSGVO compliance for Flinkform Pro.
 *
 * The free core discloses + exports + erases the submission data it stores.
 * Pro adds the disclosures and data-subject handling for the personal data the
 * Pro features touch:
 *
 *   - Privacy-policy content for webhooks (submission data is transmitted to
 *     third-party URLs, possibly outside the EU) and SMTP (notification mail is
 *     routed through a configured provider).
 *   - A personal-data exporter for the webhook delivery log, so a data-subject
 *     access request also reveals where + when their data was dispatched.
 *   - An erasure cascade: when submissions are deleted — manually OR via
 *     WordPress's personal-data eraser, both of which fire
 *     `flinkform_submissions_deleted` — the related webhook delivery rows are
 *     removed too. Hooking the deletion seam (rather than registering a
 *     separate email-keyed eraser) is deliberate: it is race-free (the free
 *     eraser may delete the submissions before a separate eraser could resolve
 *     them by email) and it also covers manual admin deletion. Net effect: no
 *     webhook delivery row referencing a deleted submission is ever orphaned.
 *
 * @package FlinkformPro
 * @since 0.2.6
 */

declare( strict_types = 1 );

namespace FlinkformPro;

use Flinkform\Privacy as CorePrivacy;
use FlinkformPro\Webhooks\DeliveryRepository;

defined( 'ABSPATH' ) || exit;

/**
 * Pro privacy integration (stateless — hooked callbacks).
 */
final class Privacy {

	/**
	 * Register the privacy hooks.
	 *
	 * @return void
	 */
	public function register(): void {
		add_action( 'admin_init', [ $this, 'add_privacy_policy_content' ] );
		add_filter( 'wp_privacy_personal_data_exporters', [ $this, 'register_exporter' ] );
		add_action( 'flinkform_submissions_deleted', [ $this, 'erase_deliveries_for_submissions' ] );
		add_filter( 'wp_privacy_personal_data_erasers', [ $this, 'register_eraser' ] );
	}

	/**
	 * Register the SMTP send-log personal-data eraser.
	 *
	 * The webhook delivery log is erased via the submission-deletion cascade;
	 * the mail log is keyed by recipient email instead of submission id, so it
	 * gets its own email-based eraser.
	 *
	 * @param array<string, array<string, mixed>> $erasers Registered erasers.
	 * @return array<string, array<string, mixed>>
	 */
	public function register_eraser( array $erasers ): array {
		$erasers['flinkform-pro-mail-log'] = [
			'eraser_friendly_name' => __( 'Flinkform Pro — Mail Log', 'flinkform-pro' ),
			'callback'             => [ $this, 'erase_mail_log' ],
		];

		return $erasers;
	}

	/**
	 * Erase mail-log rows addressed to the data subject.
	 *
	 * @param string $email_address The email to erase.
	 * @return array{items_removed: int, items_retained: int, messages: array<int, string>, done: bool}
	 */
	public function erase_mail_log( string $email_address ): array {
		$removed = \FlinkformPro\Smtp\MailLog::erase_for_email( $email_address );

		return [
			'items_removed'  => $removed,
			'items_retained' => 0,
			'messages'       => [],
			'done'           => true,
		];
	}

	/**
	 * Suggest privacy-policy text covering the Pro data flows.
	 *
	 * @return void
	 */
	public function add_privacy_policy_content(): void {
		if ( ! function_exists( 'wp_add_privacy_policy_content' ) ) {
			return;
		}

		// esc_html__ (not __) so a malicious translation file can never inject
		// markup into the privacy-policy page; these strings are plain prose.
		$content  = '<h2>' . esc_html__( 'Flinkform Pro — Integrations', 'flinkform-pro' ) . '</h2>';
		$content .= '<p>' . esc_html__( 'When a site administrator configures a webhook on a form, the values submitted through that form are transmitted to the external URL(s) the administrator specifies (for example Zapier, Make, n8n or a custom endpoint). Those destinations may be operated by third parties and may be located outside the European Union. Flinkform Pro records each dispatch attempt (status, response code and response body) in a delivery log on this website.', 'flinkform-pro' ) . '</p>';
		$content .= '<p>' . esc_html__( 'When the SMTP feature is enabled, notification emails generated by your forms (which may contain submitted data) are routed through the SMTP provider the administrator has configured, instead of the web server\'s default mail transport.', 'flinkform-pro' ) . '</p>';
		$content .= '<p>' . esc_html__( 'Webhook delivery-log entries tied to a submission are removed automatically when that submission is deleted or erased through a data-subject request.', 'flinkform-pro' ) . '</p>';
		$content .= '<p>' . esc_html__( 'When the SMTP send log is enabled, this website keeps a record of outgoing emails (recipient address, subject line and delivery result — never the message body). Because the SMTP feature routes all of the site\'s email, this log covers every outgoing message while it is active, not only the forms\' own notifications. Entries are deleted automatically after the configured retention period and are covered by data-subject erasure requests.', 'flinkform-pro' ) . '</p>';
		$content .= '<p>' . esc_html__( 'When a form contains a File Upload field, files visitors attach are stored in this website\'s uploads directory under randomised names. An uploaded file is deleted automatically when the submission it belongs to is deleted — whether manually, through the per-form retention period, or through a data-subject erasure request.', 'flinkform-pro' ) . '</p>';
		$content .= '<p>' . esc_html__( 'When a form has a newsletter integration enabled, the email address (and, if mapped, the name) is transmitted to the configured newsletter provider (Brevo, Mailchimp or CleverReach) — but only when the visitor has actively ticked the consent field on the form. Those providers may process the data outside the European Union; their own privacy policies apply.', 'flinkform-pro' ) . '</p>';

		wp_add_privacy_policy_content( 'Flinkform Pro', $content );
	}

	/**
	 * Register the webhook delivery-log personal-data exporter.
	 *
	 * @param array<string, array<string, mixed>> $exporters Registered exporters.
	 * @return array<string, array<string, mixed>>
	 */
	public function register_exporter( array $exporters ): array {
		$exporters['flinkform-pro-webhooks'] = [
			'exporter_friendly_name' => __( 'Flinkform Pro — Webhook Deliveries', 'flinkform-pro' ),
			'callback'               => [ $this, 'export_delivery_data' ],
		];

		return $exporters;
	}

	/**
	 * Export webhook delivery records tied to the data subject's submissions.
	 *
	 * Resolves the subject's submissions via the free core's public lookup,
	 * then reports each delivery dispatched for those submissions.
	 *
	 * @param string $email_address The email to search for.
	 * @param int    $page          Page number (1-based).
	 * @return array{data: array<int, array<string, mixed>>, done: bool}
	 */
	public function export_delivery_data( string $email_address, int $page = 1 ): array {
		$per_page = 50;

		if ( ! class_exists( CorePrivacy::class ) ) {
			return [
				'data' => [],
				'done' => true,
			];
		}

		$submission_ids = CorePrivacy::find_submission_ids_by_email( $email_address, $page, $per_page );
		$repo           = new DeliveryRepository();
		$export_data    = [];

		// Note: the delivery `response_body` is intentionally NOT exported. It
		// is the third-party endpoint's response (typically a status payload),
		// not the data subject's own data, and may itself contain unrelated
		// third-party content. It is still erased with the submission via the
		// cascade, so nothing about the subject is retained.
		foreach ( $submission_ids as $submission_id ) {
			foreach ( $repo->find_for_submission( $submission_id ) as $delivery ) {
				$items = [
					[
						'name'  => __( 'Webhook', 'flinkform-pro' ),
						'value' => (string) ( $delivery['webhook_label'] ?? $delivery['webhook_url'] ?? '' ),
					],
					[
						'name'  => __( 'Destination URL', 'flinkform-pro' ),
						'value' => (string) ( $delivery['webhook_url'] ?? '' ),
					],
					[
						'name'  => __( 'Status', 'flinkform-pro' ),
						'value' => (string) ( $delivery['status'] ?? '' ),
					],
					[
						'name'  => __( 'Response code', 'flinkform-pro' ),
						'value' => null !== ( $delivery['response_code'] ?? null ) ? (string) (int) $delivery['response_code'] : '—',
					],
					[
						'name'  => __( 'Dispatched at', 'flinkform-pro' ),
						'value' => (string) ( $delivery['updated_at'] ?? $delivery['created_at'] ?? '' ),
					],
				];

				$export_data[] = [
					'group_id'          => 'flinkform-pro-webhook-deliveries',
					'group_label'       => __( 'Flinkform Pro — Webhook Deliveries', 'flinkform-pro' ),
					'group_description' => __( 'Records of form submissions dispatched to external webhook endpoints.', 'flinkform-pro' ),
					'item_id'           => 'flinkform-webhook-delivery-' . (int) ( $delivery['id'] ?? 0 ),
					'data'              => $items,
				];
			}
		}

		return [
			'data' => $export_data,
			// Done once the submission lookup returns a short (final) page —
			// mirrors the free core exporter's pagination contract.
			'done' => count( $submission_ids ) < $per_page,
		];
	}

	/**
	 * Cascade-delete webhook delivery rows for deleted submissions.
	 *
	 * Hooked on `flinkform_submissions_deleted` (fired by the free core for both
	 * manual deletion and WordPress's personal-data eraser).
	 *
	 * @param array<int, int> $submission_ids Submission ids that were deleted.
	 * @return void
	 */
	public function erase_deliveries_for_submissions( $submission_ids ): void {
		if ( ! is_array( $submission_ids ) || empty( $submission_ids ) ) {
			return;
		}

		( new DeliveryRepository() )->delete_for_submissions( $submission_ids );
	}
}
