<?php
/**
 * GDPR / DSGVO compliance for PerForm Pro.
 *
 * The free core discloses + exports + erases the submission data it stores.
 * Pro adds the disclosures and data-subject handling for the personal data the
 * Pro features touch:
 *
 *   - Privacy-policy content for webhooks (submission data is transmitted to
 *     third-party URLs, possibly outside the EU) and SMTP (notification mail is
 *     routed through a configured provider).
 *   - A personal-data exporter for the webhook delivery log, so a data-subject
 *     access request also reveals where + when their data was dispatched.
 *   - An erasure cascade: when submissions are deleted — manually OR via
 *     WordPress's personal-data eraser, both of which fire
 *     `perform_submissions_deleted` — the related webhook delivery rows are
 *     removed too. Hooking the deletion seam (rather than registering a
 *     separate email-keyed eraser) is deliberate: it is race-free (the free
 *     eraser may delete the submissions before a separate eraser could resolve
 *     them by email) and it also covers manual admin deletion. Net effect: no
 *     webhook delivery row referencing a deleted submission is ever orphaned.
 *
 * @package PerFormPro
 * @since 0.2.6
 */

declare( strict_types = 1 );

namespace PerFormPro;

use PerForm\Privacy as CorePrivacy;
use PerFormPro\Webhooks\DeliveryRepository;

defined( 'ABSPATH' ) || exit;

/**
 * Pro privacy integration (stateless — hooked callbacks).
 */
final class Privacy {

	/**
	 * Register the privacy hooks.
	 *
	 * @return void
	 */
	public function register(): void {
		add_action( 'admin_init', [ $this, 'add_privacy_policy_content' ] );
		add_filter( 'wp_privacy_personal_data_exporters', [ $this, 'register_exporter' ] );
		add_action( 'perform_submissions_deleted', [ $this, 'erase_deliveries_for_submissions' ] );
	}

	/**
	 * Suggest privacy-policy text covering the Pro data flows.
	 *
	 * @return void
	 */
	public function add_privacy_policy_content(): void {
		if ( ! function_exists( 'wp_add_privacy_policy_content' ) ) {
			return;
		}

		$content  = '<h2>' . __( 'PerForm Pro — Integrations', 'perform-forms-pro' ) . '</h2>';
		$content .= '<p>' . __( 'When a site administrator configures a webhook on a form, the values submitted through that form are transmitted to the external URL(s) the administrator specifies (for example Zapier, Make, n8n or a custom endpoint). Those destinations may be operated by third parties and may be located outside the European Union. PerForm Pro records each dispatch attempt (status, response code and response body) in a delivery log on this website.', 'perform-forms-pro' ) . '</p>';
		$content .= '<p>' . __( 'When the SMTP feature is enabled, notification emails generated by your forms (which may contain submitted data) are routed through the SMTP provider the administrator has configured, instead of the web server\'s default mail transport.', 'perform-forms-pro' ) . '</p>';
		$content .= '<p>' . __( 'Webhook delivery-log entries tied to a submission are removed automatically when that submission is deleted or erased through a data-subject request.', 'perform-forms-pro' ) . '</p>';

		wp_add_privacy_policy_content( 'PerForm Pro', $content );
	}

	/**
	 * Register the webhook delivery-log personal-data exporter.
	 *
	 * @param array<string, array<string, mixed>> $exporters Registered exporters.
	 * @return array<string, array<string, mixed>>
	 */
	public function register_exporter( array $exporters ): array {
		$exporters['perform-forms-pro-webhooks'] = [
			'exporter_friendly_name' => __( 'PerForm Pro — Webhook Deliveries', 'perform-forms-pro' ),
			'callback'               => [ $this, 'export_delivery_data' ],
		];

		return $exporters;
	}

	/**
	 * Export webhook delivery records tied to the data subject's submissions.
	 *
	 * Resolves the subject's submissions via the free core's public lookup,
	 * then reports each delivery dispatched for those submissions.
	 *
	 * @param string $email_address The email to search for.
	 * @param int    $page          Page number (1-based).
	 * @return array{data: array<int, array<string, mixed>>, done: bool}
	 */
	public function export_delivery_data( string $email_address, int $page = 1 ): array {
		$per_page = 50;

		if ( ! class_exists( CorePrivacy::class ) ) {
			return [
				'data' => [],
				'done' => true,
			];
		}

		$submission_ids = CorePrivacy::find_submission_ids_by_email( $email_address, $page, $per_page );
		$repo           = new DeliveryRepository();
		$export_data    = [];

		foreach ( $submission_ids as $submission_id ) {
			foreach ( $repo->find_for_submission( $submission_id ) as $delivery ) {
				$items = [
					[
						'name'  => __( 'Webhook', 'perform-forms-pro' ),
						'value' => (string) ( $delivery['webhook_label'] ?? $delivery['webhook_url'] ?? '' ),
					],
					[
						'name'  => __( 'Destination URL', 'perform-forms-pro' ),
						'value' => (string) ( $delivery['webhook_url'] ?? '' ),
					],
					[
						'name'  => __( 'Status', 'perform-forms-pro' ),
						'value' => (string) ( $delivery['status'] ?? '' ),
					],
					[
						'name'  => __( 'Response code', 'perform-forms-pro' ),
						'value' => null !== ( $delivery['response_code'] ?? null ) ? (string) (int) $delivery['response_code'] : '—',
					],
					[
						'name'  => __( 'Dispatched at', 'perform-forms-pro' ),
						'value' => (string) ( $delivery['updated_at'] ?? $delivery['created_at'] ?? '' ),
					],
				];

				$export_data[] = [
					'group_id'          => 'perform-pro-webhook-deliveries',
					'group_label'       => __( 'PerForm Pro — Webhook Deliveries', 'perform-forms-pro' ),
					'group_description' => __( 'Records of form submissions dispatched to external webhook endpoints.', 'perform-forms-pro' ),
					'item_id'           => 'perform-webhook-delivery-' . (int) ( $delivery['id'] ?? 0 ),
					'data'              => $items,
				];
			}
		}

		return [
			'data' => $export_data,
			// Done once the submission lookup returns a short (final) page —
			// mirrors the free core exporter's pagination contract.
			'done' => count( $submission_ids ) < $per_page,
		];
	}

	/**
	 * Cascade-delete webhook delivery rows for deleted submissions.
	 *
	 * Hooked on `perform_submissions_deleted` (fired by the free core for both
	 * manual deletion and WordPress's personal-data eraser).
	 *
	 * @param array<int, int> $submission_ids Submission ids that were deleted.
	 * @return void
	 */
	public function erase_deliveries_for_submissions( $submission_ids ): void {
		if ( ! is_array( $submission_ids ) || empty( $submission_ids ) ) {
			return;
		}

		( new DeliveryRepository() )->delete_for_submissions( $submission_ids );
	}
}
